### ISSUE TITLE
Install errors on MSYS2

### ISSUE THREAD

**Issue by lovetox** [malja/zroya#11]
```
$ pip3 install git+https://github.com/malja/zroya.git
Collecting git+https://github.com/malja/zroya.git
  Cloning https://github.com/malja/zroya.git to c:/users/user/appdata/local/temp/pip-req-build-tju6m2a4
Building wheels for collected packages: zroya
  Running setup.py bdist_wheel for zroya ... error
  Complete output from command C:/msys64/mingw32/bin/python3.exe -u -c "import setuptools, tokenize;__file__='C:/Users/user/AppData/Local/Temp/pip-req-build-tju6m2a4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:/Users/user/AppData/Local/Temp/pip-wheel-womx3zwx --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building '_zroya' extension
  creating build
  creating build/temp.mingw-3.6
  creating build/temp.mingw-3.6/module
  C:\msys64\mingw32\bin/i686-w64-mingw32-gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -I./module -IC:/msys64/mingw32/include/python3.6m -c ./module/event_handler.cpp -o build/temp.mingw-3.6/./module/event_handler.o /utf-8
  i686-w64-mingw32-gcc: error: /utf-8: No such file or directory
  error: command 'C:\\msys64\\mingw32\\bin/i686-w64-mingw32-gcc.exe' failed with exit status 1

  ----------------------------------------
  Failed building wheel for zroya
  Running setup.py clean for zroya
Failed to build zroya
Installing collected packages: zroya
  Running setup.py install for zroya ... error
    Complete output from command C:/msys64/mingw32/bin/python3.exe -u -c "import setuptools, tokenize;__file__='C:/Users/user/AppData/Local/Temp/pip-req-build-tju6m2a4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:/Users/user/AppData/Local/Temp/pip-record-a6jjlec6/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building '_zroya' extension
    creating build
    creating build/temp.mingw-3.6
    creating build/temp.mingw-3.6/module
    C:\msys64\mingw32\bin/i686-w64-mingw32-gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -I./module -IC:/msys64/mingw32/include/python3.6m -c ./module/event_handler.cpp -o build/temp.mingw-3.6/./module/event_handler.o /utf-8
    i686-w64-mingw32-gcc: error: /utf-8: No such file or directory
    error: command 'C:\\msys64\\mingw32\\bin/i686-w64-mingw32-gcc.exe' failed with exit status 1

    ----------------------------------------
Command "C:/msys64/mingw32/bin/python3.exe -u -c "import setuptools, tokenize;__file__='C:/Users/user/AppData/Local/Temp/pip-req-build-tju6m2a4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:/Users/user/AppData/Local/Temp/pip-record-a6jjlec6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:/Users/user/AppData/Local/Temp/pip-req-build-tju6m2a4/
```

and via pypi

```
$ pip3 install zroya
Collecting zroya
  Using cached https://files.pythonhosted.org/packages/6a/7d/e61a4871e0e0789165260ea20b9acea29b6794d9e51286457ea3f2adc241/zroya-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:/Users/user/AppData/Local/Temp/pip-install-8tztgf4l/zroya/setup.py", line 6, in <module>
        from generate_stubs import GenerateStubFile
    ModuleNotFoundError: No module named 'generate_stubs'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:/Users/USER/AppData/Local/Temp/pip-install-8tztgf4l/zroya/
```

**Comment by malja** [comment]
Hi @lovetox,

thank you for bug report. 

The first issue was caused by `/utf-8` parameter, which is not supported by gcc. I removed it.

The second one seems to be a problem with pypi packaging. It is working for me, but the installation might have been affected by previous installations I did during testing.

Version 0.2.2b (available both from pypi and source) should address those issues. Please test it out.

**Comment by lovetox** [comment]
I encounter now a different error

```
Installing collected packages: zroya
  Running setup.py install for zroya ... error
    Complete output from command C:/msys64/mingw32/bin/python3.exe -u -c "import                                                    setuptools, tokenize;__file__='C:/Users/Philipp/AppData/Local/Temp/pip-req-buil                                                   d-rdsy8z4t/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().r                                                   eplace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --                                                   record C:/Users/Philipp/AppData/Local/Temp/pip-record-3sx75n8b/install-record.tx                                                   t --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.mingw-3.6
    creating build/lib.mingw-3.6/zroya
    copying zroya/dismiss_reason.py -> build/lib.mingw-3.6/zroya
    copying zroya/template_enums.py -> build/lib.mingw-3.6/zroya
    copying zroya/version.py -> build/lib.mingw-3.6/zroya
    copying zroya/__init__.py -> build/lib.mingw-3.6/zroya
    running build_ext
    building '_zroya' extension
    creating build/temp.mingw-3.6
    creating build/temp.mingw-3.6/module
    C:\msys64\mingw32\bin/i686-w64-mingw32-gcc.exe -Wno-unused-result -Wsign-com                                                   pare -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_ST                                                   DIO=1 -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_S                                                   TDIO=1 -DNDEBUG -I./module -IC:/msys64/mingw32/include/python3.6m -c ./module/ev                                                   ent_handler.cpp -o build/temp.mingw-3.6/./module/event_handler.o
    In file included from ./module/event_handler.h:3:0,
                     from ./module/event_handler.cpp:1:
    ./module/wintoastlib.h:7:10: fatal error: wrl/implements.h: No such file or                                                    directory
     #include <wrl/implements.h>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'C:\\msys64\\mingw32\\bin/i686-w64-mingw32-gcc.exe' failed wi                                                   th exit status 1
```

the error on pypi is the same, do i miss a dependency for that generate_stubs file?

**Comment by malja** [comment]
Are you sure Windows Runtime Library ([WRL](https://msdn.microsoft.com/en-us/library/hh438466.aspx)) is supported by MSYS? According to this [StackOverflow thread](https://stackoverflow.com/questions/12909139/can-windows-store-applications-be-built-with-mingw), it isn't. Maybe things haven't changed since 2013...

About the `generate_stubs.py`. It's part of the package. You were most likely installing from source tar, which didn't have the file in it.

I added all required files to source tar. With Visual Studio as default compiler and [Visual C++ Redistributable installed](https://www.microsoft.com/en-US/download/details.aspx?id=48145) it works fine.

**Comment by lovetox** [comment]
i tested with a normal python installation on windows and it works fine there.

> With Visual Studio as default compiler and Visual C++ Redistributable installed it works fine.

do you mean with MSYS?

i think we can use msvc compiler also inside msys for building, but i get unrelated errors with this.

hm bummer, we build our application with MSYS, so getting this to work there somehow would be great

**Comment by malja** [comment]
> i tested with a normal python installation on windows and it works fine there.

I'm glad to hear that. It's indeed MSYS related problem.

> hm bummer, we build our application with MSYS, so getting this to work there somehow would be great

The problem is, MSYS2 has only a limited support for WRL. For instance, there are missing header files and `implements.h` is among them. This was my first experience with MSYS2 at all, so I wrote to mailing list for help ([link](https://sourceforge.net/p/msys2/mailman/msys2-users/thread/97e48697-1fd3-911e-ed2a-475db0bb82a1%40gmail.com/#msg36311274)). Liu Hao practically confirmed what I said. On top of that, he pointed out that writing a header file which works both under Windows and MSYS2 may be challenging process. 

At the moment I don't have enough time for implementing WRL support required for zroya to work with MSYS2. But feel free to do it yourself.

**Comment by lovetox** [comment]
Thanks for looking into that.

If you dont have the time to target MSYS2 for now, i will close this issue. If more people want it to happen they can reopen.
