### ISSUE TITLE
Example not working correctly

### ISSUE THREAD

**Issue by lovetox** [malja/zroya#7]
Hi,

Great project, there are many python windows projects that can use this !

you mention pypiwin32 in your readme, i just want to bring it to your attention that this is probably a fork of the original project pywin32

https://github.com/mhammond/pywin32

they are nearly identical still, but you should probably decide which has a better future

either way i tested with both libs and this was the error i get if execut your example

````
C:\Users\Username\Desktop>python notify.py
Python WNDPROC handler failed
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zroya-0.1.2-py3.6.egg\zroya\__init__.py", line 275, in _eventLoop
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zroya-0.1.2-py3.6.egg\zroya\__init__.py", line 248, in _onNotificationEvent
TypeError: 'NoneType' object is not callable

on clicking the notifaction

Python WNDPROC handler failed
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zroya-0.1.2-py3.6.egg\zroya\__init__.py", line 275, in _eventLoop
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zroya-0.1.2-py3.6.egg\zroya\__init__.py", line 248, in _onNotificationEvent
TypeError: click_callback() missing 1 required positional argument: 'data'
```

**Comment by malja** [comment]
First of all, thank you for bug report. 

I thought I did test this, but somehow, I missed some checks in code. It should be working now. Please download new version 0.1.3 from pypi.

> you mention pypiwin32 in your readme, i just want to bring it to your attention that this is probably a fork of the original project pywin32

Thank you for pointing out, I was not aware of this project. However I am working on new version of this project, which does not use pywin at all. I hopefully finish it soon so you guys might use it.
